### ISSUE TITLE
Modify flake to inject scaffolding version into shipyard

### ISSUE THREAD

**Issue by c12i** [darksoil-studio/tauri-plugin-holochain#18]
Hi @guillemcordoba,

We recently encountered an issue with the current setup guide for the P2P Shipyard development environment, as described in the [Darksoil documentation](https://darksoil.studio/p2p-shipyard/documentation/how-to-create-an-end-user-happ.html).

## Issue:
The current flake setup introduces another level of locking for the scaffolding version. For better stability and maintainability of the scaffolded hApps, I suggest modifying the flake to inject versions directly into Shipyard.

See this thread for reference: https://github.com/holochain/scaffolding/issues/328. A new version of scaffolding was not immediately available for use after running `nix flake update`; the `flake.lock` file of this repo would need to be updated first.

**Comment by guillemcordoba** [comment]
Thanks, fixed in latest master, the shipyard nix does not add the holochain packages in the shell anymore, instead it requires the consuming flake to do so.
